from PyQt5 import QtCore, QtGui, QtWidgets
import configparser
import requests
import win32api

class Ui_SensorSettings(object):
    #to add data connection url in config.ini
    def dataConnection (self, text):    
        try:    
            config = configparser.ConfigParser()
            config.read('config.ini')
            config.set("Sensor_settings","sensor1Source",text)
            #print (config.get("Sensor_settings","sensor1Source"))
            with open('config.ini', 'w') as configfile:
                config.write(configfile)
        except Exception as x:
            win32api.MessageBox(0,f'An error occured! \n {x}','Error occured',0x00000010)
        
    #to get type of sensor in config.ini
    def sensorType (self, index):
        try:
            config = configparser.ConfigParser()
            config.read('config.ini')
            typeS = self.cmbBoxType.itemText(index)
            config.set("Sensor_settings","sensor1Type", typeS)
            print (index)
            with open('config.ini', 'w') as configfile:
                config.write(configfile) 
        except Exception as x:
            win32api.MessageBox(0,f'An error occured! \n {x}','Error occured',0x00000010)  
        #self.cmbBoxType.currentIndex(config.set("Sensor_settings","sensor1Type"))
    #to get spinbox values
    def tempSet(self, path):
        try:
            config = configparser.ConfigParser()
            config.read('config.ini')
            config.set("Sensor_settings","sensor1TMinValue", str(self.spinMinT.value()))
            config.set("Sensor_settings","sensor1TMaxValue", str(self.spinMaxT.value()))
            config.set("Sensor_settings","sensor1HMinValue", str(self.spinMinH.value()))
            config.set("Sensor_settings","sensor1HMaxValue", str(self.spinMaxH.value()))
            #print ("Curren value is: " + str(self.spinMinT.value()))
            with open('config.ini', 'w') as configfile:
                config.write(configfile)
        except Exception as x:
            win32api.MessageBox(0,f'An error occured! \n {x}','Error occured',0x00000010)
        
    #to activate the sensor
    def activateCheck (self):       
        try:
            """config = configparser.ConfigParser()
            config.read('config.ini')"""
            if self.checkBoxAct.isChecked()==True:                
                #config.set('Sensor_rules','sensor1statue','1')
                self.spinMinT.setEnabled(True)
                self.spinMaxT.setEnabled(True)
                self.spinMinH.setEnabled(True)
                self.spinMaxH.setEnabled(True)
                self.cmbBoxType.setEnabled(True)
                self.lineUrl.setEnabled(True)
                #print ("Sensor activated!")
            else:
                #config.set('Sensor_rules','sensor1statue','0')
                self.spinMinT.setEnabled(False)
                self.spinMaxT.setEnabled(False)
                self.spinMinH.setEnabled(False)
                self.spinMaxH.setEnabled(False)
                self.cmbBoxType.setEnabled(False)
                self.lineUrl.setEnabled(False)
                #print ("Disactivated")
        except Exception as x:
            win32api.MessageBox(0,f'An error occured! \n {x}','Error occured',0x00000010)
                        
    def setupUi(self, SensorSettings):
        SensorSettings.setObjectName("SensorSettings")
        SensorSettings.setWindowModality(QtCore.Qt.NonModal)
        SensorSettings.resize(652, 642)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("settingsIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SensorSettings.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(SensorSettings)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(SensorSettings)
        self.scrollArea.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 615, 593))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        
        config = configparser.ConfigParser()
        config.read('config.ini')
        #-------------------sensor area-------------------       
        self.sensor1Area = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.sensor1Area.setObjectName("sensor1Area")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sensor1Area)
        self.gridLayout_2.setObjectName("gridLayout_2")
        
        #to activate sensor
        self.checkBoxAct = QtWidgets.QCheckBox(self.sensor1Area)
        self.checkBoxAct.setObjectName("checkBoxAct")
        self.gridLayout_2.addWidget(self.checkBoxAct, 0, 0, 1, 1)
        self.checkBoxAct.stateChanged.connect(self.activateCheck)
        self.lblType = QtWidgets.QLabel(self.sensor1Area)
        self.lblType.setObjectName("lblType")
        self.gridLayout_2.addWidget(self.lblType, 1, 0, 1, 1)
        
        #to get combobox selected item func
        self.cmbBoxType = QtWidgets.QComboBox(self.sensor1Area)
        self.cmbBoxType.setObjectName("cmbBoxType")
        self.cmbBoxType.addItem("")
        self.cmbBoxType.addItem("")
        self.cmbBoxType.addItem("")
        self.gridLayout_2.addWidget(self.cmbBoxType, 1, 1, 1, 3)
        """x = config.get("Sensor_settings","sensor1Type")"""
        #self.cmbBoxType.getCurrentIndex()
        #self.cmbBoxType.itemText()
        self.cmbBoxType.activated.connect(self.sensorType)      
        self.cmbBoxType.setCurrentIndex(['Temperature - Humidity','Temperature','Light'].index(config.get("Sensor_settings","sensor1Type")))
        self.lblData = QtWidgets.QLabel(self.sensor1Area)
        self.lblData.setObjectName("lblData")
        self.gridLayout_2.addWidget(self.lblData, 2, 0, 1, 1)
        
        
        #to connect dataConnection func
        self.lineUrl = QtWidgets.QLineEdit(self.sensor1Area)        
        self.lineUrl.setObjectName("lineUrl")
        self.gridLayout_2.addWidget(self.lineUrl, 2, 1, 1, 3)
        self.lineUrl.setText(config.get("Sensor_settings","sensor1Source"))
        self.lineUrl.textChanged.connect(self.dataConnection)
        
        
        self.lblMinT = QtWidgets.QLabel(self.sensor1Area)
        self.lblMinT.setObjectName("lblMinT")
        self.gridLayout_2.addWidget(self.lblMinT, 3, 0, 1, 1) 
        self.spinMinT = QtWidgets.QDoubleSpinBox(self.sensor1Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMinT.sizePolicy().hasHeightForWidth())
        self.spinMinT.setSizePolicy(sizePolicy)
        self.spinMinT.setObjectName("spinMinT")
        self.gridLayout_2.addWidget(self.spinMinT, 3, 1, 1, 1)
       

        self.lblMaxT = QtWidgets.QLabel(self.sensor1Area)
        self.lblMaxT.setObjectName("lblMaxT")
        self.gridLayout_2.addWidget(self.lblMaxT, 4, 0, 1, 1)
        self.spinMaxT = QtWidgets.QDoubleSpinBox(self.sensor1Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMaxT.sizePolicy().hasHeightForWidth())
        self.spinMaxT.setSizePolicy(sizePolicy)
        self.spinMaxT.setObjectName("spinMaxT")
        self.gridLayout_2.addWidget(self.spinMaxT, 4, 1, 1, 1)
        
        
        self.lblMinH = QtWidgets.QLabel(self.sensor1Area)
        self.lblMinH.setObjectName("lblMinH")
        self.gridLayout_2.addWidget(self.lblMinH, 5, 0, 1, 1)
        self.spinMinH = QtWidgets.QDoubleSpinBox(self.sensor1Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMinH.sizePolicy().hasHeightForWidth())
        self.spinMinH.setSizePolicy(sizePolicy)
        self.spinMinH.setObjectName("spinMinH")
        self.gridLayout_2.addWidget(self.spinMinH, 5, 1, 1, 1)
        self.lblMaxH = QtWidgets.QLabel(self.sensor1Area)
        self.lblMaxH.setObjectName("lblMaxH")
        self.gridLayout_2.addWidget(self.lblMaxH, 6, 0, 1, 1)
        self.spinMaxH = QtWidgets.QDoubleSpinBox(self.sensor1Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMaxH.sizePolicy().hasHeightForWidth())
        self.spinMaxH.setSizePolicy(sizePolicy)
        self.spinMaxH.setObjectName("spinMaxH")
        self.gridLayout_2.addWidget(self.spinMaxH, 6, 1, 1, 1)
        self.lblLight = QtWidgets.QLabel(self.sensor1Area)
        self.lblLight.setObjectName("lblLight")
        self.gridLayout_2.addWidget(self.lblLight, 6, 2, 1, 1)
        self.cmbBoxAlert = QtWidgets.QComboBox(self.sensor1Area)
        self.cmbBoxAlert.setObjectName("cmbBoxAlert")
        self.cmbBoxAlert.addItem("")
        self.cmbBoxAlert.addItem("")
        self.gridLayout_2.addWidget(self.cmbBoxAlert, 6, 3, 1, 1)
        self.lblBattery = QtWidgets.QLabel(self.sensor1Area)
        self.lblBattery.setObjectName("lblBattery")
        self.gridLayout_2.addWidget(self.lblBattery, 7, 0, 1, 1)
        self.batteryBar = QtWidgets.QProgressBar(self.sensor1Area)
        
        #battery information
        sensor1Source = config.get('Sensor_settings','sensor1Source')                            
        json_data = requests.get(sensor1Source).json()
        batteryInfo = int(47)#json_data['battery']
        self.batteryBar.setProperty("value", int(batteryInfo))
        self.batteryBar.setObjectName("batteryBar")
        self.gridLayout_2.addWidget(self.batteryBar, 7, 1, 1, 3)
        self.gridLayout_6.addWidget(self.sensor1Area, 0, 0, 1, 1)
        
        #spinBox values to tempSet func
        self.spinMinT.valueChanged.connect(self.tempSet)
        self.spinMaxT.valueChanged.connect(self.tempSet)
        self.spinMinH.valueChanged.connect(self.tempSet)
        self.spinMaxH.valueChanged.connect(self.tempSet)
        
        #set default as disabled
        self.spinMinT.setEnabled(False)
        self.spinMaxT.setEnabled(False)
        self.spinMinH.setEnabled(False)
        self.spinMaxH.setEnabled(False)
        self.cmbBoxType.setEnabled(False)
        self.lineUrl.setEnabled(False)

        self.spinMinT.setValue(float(config.get("Sensor_settings","sensor1TMinValue")))
        self.spinMaxT.setValue(float(config.get("Sensor_settings","sensor1TMaxValue")))
        self.spinMinH.setValue(float(config.get("Sensor_settings","sensor1HMinValue")))
        self.spinMaxH.setValue(float(config.get("Sensor_settings","sensor1HMaxValue")))
        
        #-------------------sensor area 2------------------- 
        self.sensor2Area = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.sensor2Area.setObjectName("sensor2Area")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.sensor2Area)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBoxAct2 = QtWidgets.QCheckBox(self.sensor2Area)
        self.checkBoxAct2.setObjectName("checkBoxAct2")
        self.gridLayout_3.addWidget(self.checkBoxAct2, 0, 0, 1, 1)
        self.lblType2 = QtWidgets.QLabel(self.sensor2Area)
        self.lblType2.setObjectName("lblType2")
        self.gridLayout_3.addWidget(self.lblType2, 1, 0, 1, 1)
        self.cmbBoxType2 = QtWidgets.QComboBox(self.sensor2Area)
        self.cmbBoxType2.setObjectName("cmbBoxType2")
        self.cmbBoxType2.addItem("")
        self.cmbBoxType2.addItem("")
        self.cmbBoxType2.addItem("")
        self.gridLayout_3.addWidget(self.cmbBoxType2, 1, 1, 1, 3)
        self.lblData2 = QtWidgets.QLabel(self.sensor2Area)
        self.lblData2.setObjectName("lblData2")
        self.gridLayout_3.addWidget(self.lblData2, 2, 0, 1, 1)
        self.lineUrl2 = QtWidgets.QLineEdit(self.sensor2Area)
        self.lineUrl2.setText("")
        self.lineUrl2.setObjectName("lineUrl2")
        self.gridLayout_3.addWidget(self.lineUrl2, 2, 1, 1, 3)
        self.lblMinT2 = QtWidgets.QLabel(self.sensor2Area)
        self.lblMinT2.setObjectName("lblMinT2")
        self.gridLayout_3.addWidget(self.lblMinT2, 3, 0, 1, 1)
        self.spinMinT2 = QtWidgets.QDoubleSpinBox(self.sensor2Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMinT2.sizePolicy().hasHeightForWidth())
        self.spinMinT2.setSizePolicy(sizePolicy)
        self.spinMinT2.setObjectName("spinMinT2")
        self.gridLayout_3.addWidget(self.spinMinT2, 3, 1, 1, 1)
        self.lblMaxT2 = QtWidgets.QLabel(self.sensor2Area)
        self.lblMaxT2.setObjectName("lblMaxT2")
        self.gridLayout_3.addWidget(self.lblMaxT2, 4, 0, 1, 1)
        self.spinMaxT2 = QtWidgets.QDoubleSpinBox(self.sensor2Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMaxT2.sizePolicy().hasHeightForWidth())
        self.spinMaxT2.setSizePolicy(sizePolicy)
        self.spinMaxT2.setObjectName("spinMaxT2")
        self.gridLayout_3.addWidget(self.spinMaxT2, 4, 1, 1, 1)
        self.lblMinH2 = QtWidgets.QLabel(self.sensor2Area)
        self.lblMinH2.setObjectName("lblMinH2")
        self.gridLayout_3.addWidget(self.lblMinH2, 5, 0, 1, 1)
        self.spinMinH2 = QtWidgets.QDoubleSpinBox(self.sensor2Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMinH2.sizePolicy().hasHeightForWidth())
        self.spinMinH2.setSizePolicy(sizePolicy)
        self.spinMinH2.setObjectName("spinMinH2")
        self.gridLayout_3.addWidget(self.spinMinH2, 5, 1, 1, 1)
        self.lblMaxH2 = QtWidgets.QLabel(self.sensor2Area)
        self.lblMaxH2.setObjectName("lblMaxH2")
        self.gridLayout_3.addWidget(self.lblMaxH2, 6, 0, 1, 1)
        self.spinMaxH2 = QtWidgets.QDoubleSpinBox(self.sensor2Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMaxH2.sizePolicy().hasHeightForWidth())
        self.spinMaxH2.setSizePolicy(sizePolicy)
        self.spinMaxH2.setObjectName("spinMaxH2")
        self.gridLayout_3.addWidget(self.spinMaxH2, 6, 1, 1, 1)
        self.lblLight2 = QtWidgets.QLabel(self.sensor2Area)
        self.lblLight2.setObjectName("lblLight2")
        self.gridLayout_3.addWidget(self.lblLight2, 6, 2, 1, 1)
        self.cmbBoxAlert2 = QtWidgets.QComboBox(self.sensor2Area)
        self.cmbBoxAlert2.setObjectName("cmbBoxAlert2")
        self.cmbBoxAlert2.addItem("")
        self.cmbBoxAlert2.addItem("")
        self.gridLayout_3.addWidget(self.cmbBoxAlert2, 6, 3, 1, 1)
        self.lblBattery2 = QtWidgets.QLabel(self.sensor2Area)
        self.lblBattery2.setObjectName("lblBattery2")
        self.gridLayout_3.addWidget(self.lblBattery2, 7, 0, 1, 1)
        self.batteryBar2 = QtWidgets.QProgressBar(self.sensor2Area)
        self.batteryBar2.setProperty("value", 24)
        self.batteryBar2.setObjectName("batteryBar2")
        self.gridLayout_3.addWidget(self.batteryBar2, 7, 1, 1, 3)
        self.gridLayout_6.addWidget(self.sensor2Area, 0, 1, 1, 1)
       
       
        #-------------------sensor area 3------------------- 
        self.sensor3Area = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.sensor3Area.setObjectName("sensor3Area")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.sensor3Area)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.checkBoxAct3 = QtWidgets.QCheckBox(self.sensor3Area)
        self.checkBoxAct3.setObjectName("checkBoxAct3")
        self.gridLayout_4.addWidget(self.checkBoxAct3, 0, 0, 1, 1)
        self.lblType3 = QtWidgets.QLabel(self.sensor3Area)
        self.lblType3.setObjectName("lblType3")
        self.gridLayout_4.addWidget(self.lblType3, 1, 0, 1, 1)
        self.cmbBoxType3 = QtWidgets.QComboBox(self.sensor3Area)
        self.cmbBoxType3.setObjectName("cmbBoxType3")
        self.cmbBoxType3.addItem("")
        self.cmbBoxType3.addItem("")
        self.cmbBoxType3.addItem("")
        self.gridLayout_4.addWidget(self.cmbBoxType3, 1, 1, 1, 3)
        self.lblData3 = QtWidgets.QLabel(self.sensor3Area)
        self.lblData3.setObjectName("lblData3")
        self.gridLayout_4.addWidget(self.lblData3, 2, 0, 1, 1)
        self.lineUrl3 = QtWidgets.QLineEdit(self.sensor3Area)
        self.lineUrl3.setText("")
        self.lineUrl3.setObjectName("lineUrl3")
        self.gridLayout_4.addWidget(self.lineUrl3, 2, 1, 1, 3)
        self.lblMinT3 = QtWidgets.QLabel(self.sensor3Area)
        self.lblMinT3.setObjectName("lblMinT3")
        self.gridLayout_4.addWidget(self.lblMinT3, 3, 0, 1, 1)
        self.spinMinT3 = QtWidgets.QDoubleSpinBox(self.sensor3Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMinT3.sizePolicy().hasHeightForWidth())
        self.spinMinT3.setSizePolicy(sizePolicy)
        self.spinMinT3.setObjectName("spinMinT3")
        self.gridLayout_4.addWidget(self.spinMinT3, 3, 1, 1, 1)
        self.lblMaxT3 = QtWidgets.QLabel(self.sensor3Area)
        self.lblMaxT3.setObjectName("lblMaxT3")
        self.gridLayout_4.addWidget(self.lblMaxT3, 4, 0, 1, 1)
        self.spinMaxT3 = QtWidgets.QDoubleSpinBox(self.sensor3Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMaxT3.sizePolicy().hasHeightForWidth())
        self.spinMaxT3.setSizePolicy(sizePolicy)
        self.spinMaxT3.setObjectName("spinMaxT3")
        self.gridLayout_4.addWidget(self.spinMaxT3, 4, 1, 1, 1)
        self.lblMinH3 = QtWidgets.QLabel(self.sensor3Area)
        self.lblMinH3.setObjectName("lblMinH3")
        self.gridLayout_4.addWidget(self.lblMinH3, 5, 0, 1, 1)
        self.spinMinH3 = QtWidgets.QDoubleSpinBox(self.sensor3Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMinH3.sizePolicy().hasHeightForWidth())
        self.spinMinH3.setSizePolicy(sizePolicy)
        self.spinMinH3.setObjectName("spinMinH3")
        self.gridLayout_4.addWidget(self.spinMinH3, 5, 1, 1, 1)
        self.lblMaxH3 = QtWidgets.QLabel(self.sensor3Area)
        self.lblMaxH3.setObjectName("lblMaxH3")
        self.gridLayout_4.addWidget(self.lblMaxH3, 6, 0, 1, 1)
        self.spinMaxH3 = QtWidgets.QDoubleSpinBox(self.sensor3Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMaxH3.sizePolicy().hasHeightForWidth())
        self.spinMaxH3.setSizePolicy(sizePolicy)
        self.spinMaxH3.setObjectName("spinMaxH3")
        self.gridLayout_4.addWidget(self.spinMaxH3, 6, 1, 1, 1)
        self.lblLight3 = QtWidgets.QLabel(self.sensor3Area)
        self.lblLight3.setObjectName("lblLight3")
        self.gridLayout_4.addWidget(self.lblLight3, 6, 2, 1, 1)
        self.cmbBoxAlert3 = QtWidgets.QComboBox(self.sensor3Area)
        self.cmbBoxAlert3.setObjectName("cmbBoxAlert3")
        self.cmbBoxAlert3.addItem("")
        self.cmbBoxAlert3.addItem("")
        self.gridLayout_4.addWidget(self.cmbBoxAlert3, 6, 3, 1, 1)
        self.lblBattery3 = QtWidgets.QLabel(self.sensor3Area)
        self.lblBattery3.setObjectName("lblBattery3")
        self.gridLayout_4.addWidget(self.lblBattery3, 7, 0, 1, 1)
        self.batteryBar3 = QtWidgets.QProgressBar(self.sensor3Area)
        self.batteryBar3.setProperty("value", 24)
        self.batteryBar3.setObjectName("batteryBar3")
        self.gridLayout_4.addWidget(self.batteryBar3, 7, 1, 1, 3)
        self.gridLayout_6.addWidget(self.sensor3Area, 1, 0, 1, 1)
       
       
        #-------------------sensor area 4------------------- 
        self.sensor4Area = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.sensor4Area.setObjectName("sensor4Area")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.sensor4Area)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.checkBoxAct4 = QtWidgets.QCheckBox(self.sensor4Area)
        self.checkBoxAct4.setObjectName("checkBoxAct4")
        self.gridLayout_5.addWidget(self.checkBoxAct4, 0, 0, 1, 1)
        self.lblType4 = QtWidgets.QLabel(self.sensor4Area)
        self.lblType4.setObjectName("lblType4")
        self.gridLayout_5.addWidget(self.lblType4, 1, 0, 1, 1)
        self.cmbBoxType4 = QtWidgets.QComboBox(self.sensor4Area)
        self.cmbBoxType4.setObjectName("cmbBoxType4")
        self.cmbBoxType4.addItem("")
        self.cmbBoxType4.addItem("")
        self.cmbBoxType4.addItem("")
        self.gridLayout_5.addWidget(self.cmbBoxType4, 1, 1, 1, 3)
        self.lblData4 = QtWidgets.QLabel(self.sensor4Area)
        self.lblData4.setObjectName("lblData4")
        self.gridLayout_5.addWidget(self.lblData4, 2, 0, 1, 1)
        self.lineUrl4 = QtWidgets.QLineEdit(self.sensor4Area)
        self.lineUrl4.setText("")
        self.lineUrl4.setObjectName("lineUrl4")
        self.gridLayout_5.addWidget(self.lineUrl4, 2, 1, 1, 3)
        self.lblMinT4 = QtWidgets.QLabel(self.sensor4Area)
        self.lblMinT4.setObjectName("lblMinT4")
        self.gridLayout_5.addWidget(self.lblMinT4, 3, 0, 1, 1)
        self.spinMinT4 = QtWidgets.QDoubleSpinBox(self.sensor4Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMinT4.sizePolicy().hasHeightForWidth())
        self.spinMinT4.setSizePolicy(sizePolicy)
        self.spinMinT4.setObjectName("spinMinT4")
        self.gridLayout_5.addWidget(self.spinMinT4, 3, 1, 1, 1)
        self.lblMaxT4 = QtWidgets.QLabel(self.sensor4Area)
        self.lblMaxT4.setObjectName("lblMaxT4")
        self.gridLayout_5.addWidget(self.lblMaxT4, 4, 0, 1, 1)
        self.spinMaxT4 = QtWidgets.QDoubleSpinBox(self.sensor4Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMaxT4.sizePolicy().hasHeightForWidth())
        self.spinMaxT4.setSizePolicy(sizePolicy)
        self.spinMaxT4.setObjectName("spinMaxT4")
        self.gridLayout_5.addWidget(self.spinMaxT4, 4, 1, 1, 1)
        self.lblMinH4 = QtWidgets.QLabel(self.sensor4Area)
        self.lblMinH4.setObjectName("lblMinH4")
        self.gridLayout_5.addWidget(self.lblMinH4, 5, 0, 1, 1)
        self.spinMinH4 = QtWidgets.QDoubleSpinBox(self.sensor4Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMinH4.sizePolicy().hasHeightForWidth())
        self.spinMinH4.setSizePolicy(sizePolicy)
        self.spinMinH4.setObjectName("spinMinH4")
        self.gridLayout_5.addWidget(self.spinMinH4, 5, 1, 1, 1)
        self.lblMaxH4 = QtWidgets.QLabel(self.sensor4Area)
        self.lblMaxH4.setObjectName("lblMaxH4")
        self.gridLayout_5.addWidget(self.lblMaxH4, 6, 0, 1, 1)
        self.spinMaxH4 = QtWidgets.QDoubleSpinBox(self.sensor4Area)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinMaxH4.sizePolicy().hasHeightForWidth())
        self.spinMaxH4.setSizePolicy(sizePolicy)
        self.spinMaxH4.setObjectName("spinMaxH4")
        self.gridLayout_5.addWidget(self.spinMaxH4, 6, 1, 1, 1)
        self.lblLight4 = QtWidgets.QLabel(self.sensor4Area)
        self.lblLight4.setObjectName("lblLight4")
        self.gridLayout_5.addWidget(self.lblLight4, 6, 2, 1, 1)
        self.cmbBoxAlert4 = QtWidgets.QComboBox(self.sensor4Area)
        self.cmbBoxAlert4.setObjectName("cmbBoxAlert4")
        self.cmbBoxAlert4.addItem("")
        self.cmbBoxAlert4.addItem("")
        self.gridLayout_5.addWidget(self.cmbBoxAlert4, 6, 3, 1, 1)
        self.lblBattery4 = QtWidgets.QLabel(self.sensor4Area)
        self.lblBattery4.setObjectName("lblBattery4")
        self.gridLayout_5.addWidget(self.lblBattery4, 7, 0, 1, 1)
        self.batteryBar4 = QtWidgets.QProgressBar(self.sensor4Area)
        self.batteryBar4.setProperty("value", 10)
        self.batteryBar4.setObjectName("batteryBar4")
        self.gridLayout_5.addWidget(self.batteryBar4, 7, 1, 1, 3)
        self.gridLayout_6.addWidget(self.sensor4Area, 1, 1, 1, 1)
        
        
        
        #buttons at the top
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 1, 4)
        self.btnAddS = QtWidgets.QPushButton(SensorSettings)
        self.btnAddS.setObjectName("btnAddS")
        self.gridLayout.addWidget(self.btnAddS, 0, 0, 1, 1)
        #self.btnAddS.clicked.connect(self.addSensors)
        self.btnSave = QtWidgets.QPushButton(SensorSettings)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 0, 3, 1, 1)
        self.btnRemove = QtWidgets.QPushButton(SensorSettings)
        self.btnRemove.setObjectName("btnRemove")
        self.gridLayout.addWidget(self.btnRemove, 0, 1, 1, 1)

        self.retranslateUi(SensorSettings)
        QtCore.QMetaObject.connectSlotsByName(SensorSettings)

    def retranslateUi(self, SensorSettings):
        _translate = QtCore.QCoreApplication.translate
        SensorSettings.setWindowTitle(_translate("SensorSettings", "Sensor Settings"))
        self.sensor1Area.setTitle(_translate("SensorSettings", "Sensor 1"))
        self.checkBoxAct.setText(_translate("SensorSettings", "Activated"))
        self.lblType.setText(_translate("SensorSettings", "Type:"))
        self.cmbBoxType.setItemText(0, _translate("SensorSettings", "Temperature - Humidity"))
        self.cmbBoxType.setItemText(1, _translate("SensorSettings", "Temperature"))
        self.cmbBoxType.setItemText(2, _translate("SensorSettings", "Light"))
        self.lblData.setText(_translate("SensorSettings", "Data Connection:"))
        self.lblMinT.setText(_translate("SensorSettings", "Min Temperature:"))
        self.lblMaxT.setText(_translate("SensorSettings", "Max Temperature:"))
        self.lblMinH.setText(_translate("SensorSettings", "Min Humidity:"))
        self.lblMaxH.setText(_translate("SensorSettings", "Max Humidity:"))
        self.lblLight.setText(_translate("SensorSettings", "Light:"))
        self.cmbBoxAlert.setItemText(0, _translate("SensorSettings", "On: Alert"))
        self.cmbBoxAlert.setItemText(1, _translate("SensorSettings", "Off: Alert"))
        self.lblBattery.setText(_translate("SensorSettings", "Battery:"))
        self.sensor2Area.setTitle(_translate("SensorSettings", "Sensor 2"))
        self.checkBoxAct2.setText(_translate("SensorSettings", "Activated"))
        self.lblType2.setText(_translate("SensorSettings", "Type:"))
        self.cmbBoxType2.setItemText(0, _translate("SensorSettings", "Temperature - Humidity"))
        self.cmbBoxType2.setItemText(1, _translate("SensorSettings", "Temperature"))
        self.cmbBoxType2.setItemText(2, _translate("SensorSettings", "Light"))
        self.lblData2.setText(_translate("SensorSettings", "Data Connection:"))
        self.lblMinT2.setText(_translate("SensorSettings", "Min Temperature:"))
        self.lblMaxT2.setText(_translate("SensorSettings", "Max Temperature:"))
        self.lblMinH2.setText(_translate("SensorSettings", "Min Humidity:"))
        self.lblMaxH2.setText(_translate("SensorSettings", "Max Humidity:"))
        self.lblLight2.setText(_translate("SensorSettings", "Light:"))
        self.cmbBoxAlert2.setItemText(0, _translate("SensorSettings", "On: Alert"))
        self.cmbBoxAlert2.setItemText(1, _translate("SensorSettings", "Off: Alert"))
        self.lblBattery2.setText(_translate("SensorSettings", "Battery:"))
        self.sensor3Area.setTitle(_translate("SensorSettings", "Sensor 3"))
        self.checkBoxAct3.setText(_translate("SensorSettings", "Activated"))
        self.lblType3.setText(_translate("SensorSettings", "Type:"))
        self.cmbBoxType3.setItemText(0, _translate("SensorSettings", "Temperature - Humidity"))
        self.cmbBoxType3.setItemText(1, _translate("SensorSettings", "Temperature"))
        self.cmbBoxType3.setItemText(2, _translate("SensorSettings", "Light"))
        self.lblData3.setText(_translate("SensorSettings", "Data Connection:"))
        self.lblMinT3.setText(_translate("SensorSettings", "Min Temperature:"))
        self.lblMaxT3.setText(_translate("SensorSettings", "Max Temperature:"))
        self.lblMinH3.setText(_translate("SensorSettings", "Min Humidity:"))
        self.lblMaxH3.setText(_translate("SensorSettings", "Max Humidity:"))
        self.lblLight3.setText(_translate("SensorSettings", "Light:"))
        self.cmbBoxAlert3.setItemText(0, _translate("SensorSettings", "On: Alert"))
        self.cmbBoxAlert3.setItemText(1, _translate("SensorSettings", "Off: Alert"))
        self.lblBattery3.setText(_translate("SensorSettings", "Battery:"))
        self.sensor4Area.setTitle(_translate("SensorSettings", "Sensor 4"))
        self.checkBoxAct4.setText(_translate("SensorSettings", "Activated"))
        self.lblType4.setText(_translate("SensorSettings", "Type:"))
        self.cmbBoxType4.setItemText(0, _translate("SensorSettings", "Temperature - Humidity"))
        self.cmbBoxType4.setItemText(1, _translate("SensorSettings", "Temperature"))
        self.cmbBoxType4.setItemText(2, _translate("SensorSettings", "Light"))
        self.lblData4.setText(_translate("SensorSettings", "Data Connection:"))
        self.lblMinT4.setText(_translate("SensorSettings", "Min Temperature:"))
        self.lblMaxT4.setText(_translate("SensorSettings", "Max Temperature:"))
        self.lblMinH4.setText(_translate("SensorSettings", "Min Humidity:"))
        self.lblMaxH4.setText(_translate("SensorSettings", "Max Humidity:"))
        self.lblLight4.setText(_translate("SensorSettings", "Light:"))
        self.cmbBoxAlert4.setItemText(0, _translate("SensorSettings", "On: Alert"))
        self.cmbBoxAlert4.setItemText(1, _translate("SensorSettings", "Off: Alert"))
        self.lblBattery4.setText(_translate("SensorSettings", "Battery:"))
        self.btnAddS.setText(_translate("SensorSettings", "Add"))
        self.btnSave.setText(_translate("SensorSettings", "Save"))
        self.btnRemove.setText(_translate("SensorSettings", "Remove"))
    
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SensorSettings = QtWidgets.QWidget()
    ui = Ui_SensorSettings()
    ui.setupUi(SensorSettings)
    SensorSettings.show()
    
    sys.exit(app.exec_())
